import {
  ButtonTheme,
  ColorThemes,
  FontThemes,
  InputThemes,
  SizeThemes,
} from '../types/GlobalStylesTypes'

export const colorThemes: ColorThemes = {
  primary: {
    bgColor: 'bg-sky-600',
    hoverBgColor: 'hover:bg-sky-700',
    text: 'text-white',
    focusRing: 'focus:ring-sky-500',
    iconText: 'text-gray-600',
    hoverIconText: 'hover:text-gray-500',
    focusBorder: 'focus:border-sky-500',
    navLinkText: 'text-white',
    hoverNavLinkText: 'hover:text-gray-50',
    navMobileLinkText: 'text-sky-700',
    hoverNavMobileLinkText: 'hover:text-sky-600',
    border: 'border-sky-500',
    navBgLinkColor: 'bg-sky-50',
  },
  secondary: {
    bgColor: 'bg-sky-100',
    hoverBgColor: 'hover:bg-sky-200',
    text: 'text-sky-700',
    focusRing: 'focus:ring-sky-500',
    iconText: 'text-sky-300',
    hoverIconText: 'hover:text-sky-400',
  },
  danger: {
    bgColor: 'bg-red-100',
    hoverBgColor: 'bg-red-200',
    text: 'text-red-700',
    focusRing: 'focus:ring-red-500',
    iconText: 'text-red-500',
    hoverIconText: 'hover:text-red-400',
  },
  link: {
    text: 'text-sky-600',
    hoverText: 'hover:text-sky-500',
    iconText: '',
    hoverIconText: '',
  },
  navLink: {
    text: 'text-gray-500',
    hoverText: 'hover:text-gray-700',
    iconText: '',
    hoverIconText: '',
  },
  badge: {
    success: 'bg-green-100 text-green-800',
    pending: 'bg-yellow-100 text-yellow-800',
    warning: 'bg-yellow-100 text-yellow-800',
    danger: 'bg-red-100 text-red-800',
  },
  actionIconTextColor: {
    success: 'text-green-800 hover:text-green-700',
    pending: 'text-yellow-800 hover:text-yellow-700',
    warning: 'text-yellow-800 hover:text-yellow-700',
    danger: 'text-red-800 hover:text-red-700',
  },
  skeleton: {
    textHeavy: 'bg-gray-300',
    textLight: 'bg-gray-200',
    divideLine: 'divide-gray-200',
    border: 'border-gray-200',
  },
  checkbox: {
    text: 'text-sky-600',
    focusRing: 'focus:ring-sky-500',
    border: 'border-gray-300',
  },
}

export const sizeThemes: SizeThemes = {
  badge: {
    md: 'px-2 rounded',
    lg: 'px-2.5 rounded-md',
  },
}

export const fontThemes: FontThemes = {
  appTitle: 'text-4xl font-extrabold text-sky-600 tracking-wider',
  title: 'text-3xl font-extrabold text-gray-900 tracking-wide',
  subTitle: 'text-2xl font-extrabold text-gray-600 tracking-wide',
  default: 'text-sm text-gray-600 tracking-normal',
  link: 'text-sm',
  inputLabel: 'text-sm font-medium text-gray-700',
  inputText: 'sm:text-sm text-gray-900',
  placeholder: 'placeholder-gray-500',
}

export const buttonTheme: ButtonTheme = {
  primary: [
    colorThemes.primary.bgColor,
    colorThemes.primary.hoverBgColor,
    colorThemes.primary.text,
    colorThemes.primary.focusRing,
  ].join(' '),
  secondary: [
    colorThemes.secondary.bgColor,
    colorThemes.secondary.hoverBgColor,
    colorThemes.secondary.text,
    colorThemes.secondary.focusRing,
  ].join(' '),
  cancel: ['bg-white', 'hover:bg-gray-50', 'text-gray-700'].join(' '),
  danger: [
    colorThemes.danger.bgColor,
    colorThemes.danger.hoverBgColor,
    colorThemes.danger.text,
    colorThemes.danger.focusRing,
  ].join(' '),
  link: [
    'bg-transparent',
    'border-none',
    'shadow-none',
    'focus:ring-0',
    'outline-none',
    'rounded-none',
    colorThemes.link.text,
    colorThemes.link.hoverText,
  ].join(' '),
  navLink: [
    'bg-transparent',
    'border-transparent',
    'border-0',
    'border-b-2',
    'hover:border-gray-300',
    'shadow-none',
    'focus:ring-0',
    'outline-0',
    'rounded-none',
    colorThemes.navLink.text,
    colorThemes.navLink.hoverText,
  ].join(' '),
  icon: [colorThemes.primary.iconText, colorThemes.primary.hoverIconText].join(' '),
}

export const inputThemes: InputThemes = {
  normal: [
    'bg-white',
    'border-gray-300',
    'border-2',
    'rounded-md',
    'focus:outline-none',
    colorThemes.primary.focusRing,
    colorThemes.primary.focusBorder,
  ].join(' '),
  stackedTop: [
    'bg-white',
    'border-gray-300',
    'border',
    'appearance-none',
    'rounded-none',
    'rounded-t-md',
    'relative',
    'focus:z-10',
    'focus:outline-none',
    colorThemes.primary.focusRing,
    colorThemes.primary.focusBorder,
  ].join(' '),
  stackedBottom: [
    'bg-white',
    'border',
    'border-gray-300',
    'appearance-none',
    'rounded-none',
    'rounded-b-md',
    'relative',
    'focus:z-10',
    'focus:outline-none',
    colorThemes.primary.focusRing,
    colorThemes.primary.focusBorder,
  ].join(' '),
  error: ['text-red-900', 'border-red-300', 'focus:ring-red-500', 'focus:border-red-500'].join(' '),
  // error: {
  //   text: 'red-900',
  //   border: 'red-300',
  //   placeholder: 'red-300',
  //   focusRing: 'red-500',
  //   focusBorder: 'red-500',
  //   ariaDescribe: 'error',
  // },
}
