name: Run React Linter
on: pull_request
jobs:
  Run-ESLint:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm install
      - name: Run strict linter
        run: npm run lint:strict
